spring:
  config:
    activate:
      on-profile: local
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed

---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    baseline-on-migrate: false
    baseline-version: 0
    baseline-description: Production DB baseline - V1부터 Flyway 관리 시작